import { useState } from 'react'
import { ArrowUpRight, Check, Plus, Trash2 } from 'lucide-react'
import { createAccount, createBudget, createCategory, createTransaction, deleteAccount, deleteBudget, deleteCategory, deleteTransaction } from './api'
import type { Account, Budget, Category, Transaction } from './api'

type Section = 'transactions' | 'budgets' | 'accounts' | 'categories'
type Props = { section: Section; accounts: Account[]; categories: Category[]; transactions: Transaction[]; budgets: Budget[]; onRefresh: () => void }

function ManagementView({ section, accounts, categories, transactions, budgets, onRefresh }: Props) {
  const [showForm, setShowForm] = useState(false)
  const title = { transactions: 'Transactions', budgets: 'Budgets', accounts: 'Accounts', categories: 'Categories' }[section]
  const description = { transactions: 'Review and manage your activity.', budgets: 'Keep spending aligned with your goals.', accounts: 'Your connected financial accounts.', categories: 'Organize the way you spend and earn.' }[section]
  const items = section === 'transactions' ? transactions : section === 'budgets' ? budgets : section === 'accounts' ? accounts : categories

  async function remove(id: number) {
    if (!window.confirm('Delete this item?')) return
    if (section === 'transactions') await deleteTransaction(id)
    if (section === 'budgets') await deleteBudget(id)
    if (section === 'accounts') await deleteAccount(id)
    if (section === 'categories') await deleteCategory(id)
    onRefresh()
  }

  return <div className="management-view"><header className="management-header"><div><p className="kicker">FINTRACK / {section.toUpperCase()}</p><h1>{title}</h1><p>{description}</p></div><button className="primary-button" onClick={() => setShowForm(true)}><Plus size={18} /> Add {section === 'transactions' ? 'transaction' : section.slice(0, -1)}</button></header><div className="management-toolbar"><span>{items.length} {items.length === 1 ? 'item' : 'items'}</span><button className="filter-button">Recently added <ArrowUpRight size={14} /></button></div><div className="management-list">{items.length === 0 ? <div className="empty-state"><div><Check size={22} /></div><h2>Nothing here yet</h2><p>Create your first {section.slice(0, -1)} to see it in this list.</p><button className="outline-button" onClick={() => setShowForm(true)}><Plus size={16} /> Get started</button></div> : items.map((item) => <ManagementRow key={item.id} item={item} section={section} onDelete={() => remove(item.id)} />)}</div>{showForm && <ResourceForm section={section} accounts={accounts} categories={categories} onClose={() => setShowForm(false)} onCreated={() => { setShowForm(false); onRefresh() }} />}</div>
}

function ManagementRow({ item, section, onDelete }: { item: Account | Category | Transaction | Budget; section: Section; onDelete: () => void }) {
  if (section === 'accounts') { const account = item as Account; return <div className="management-row"><div className="row-badge violet-badge">$</div><div><strong>{account.name}</strong><span>{account.currency} account</span></div><strong>{Number(account.balance).toLocaleString('en-US', { minimumFractionDigits: 2 })}</strong><button className="delete-button" aria-label="Delete account" onClick={onDelete}><Trash2 size={16} /></button></div> }
  if (section === 'categories') { const category = item as Category; return <div className="management-row"><div className="row-badge pink-badge">{category.icon || '•'}</div><div><strong>{category.name}</strong><span>{category.type === 'INCOME' ? 'Income' : 'Expense'} category</span></div><span className="color-chip" style={{ background: category.color || '#7450b5' }} /><button className="delete-button" aria-label="Delete category" onClick={onDelete}><Trash2 size={16} /></button></div> }
  if (section === 'budgets') { const budget = item as Budget; return <div className="management-row"><div className="row-badge gold-badge">%</div><div><strong>{budget.categoryName}</strong><span>{budget.month}/{budget.year}</span></div><strong>${Number(budget.amount).toLocaleString('en-US', { minimumFractionDigits: 2 })}</strong><button className="delete-button" aria-label="Delete budget" onClick={onDelete}><Trash2 size={16} /></button></div> }
  const transaction = item as Transaction
  return <div className="management-row"><div className={`row-badge ${transaction.type === 'INCOME' ? 'violet-badge' : 'pink-badge'}`}>{transaction.type === 'INCOME' ? '+' : '-'}</div><div><strong>{transaction.description || transaction.categoryName}</strong><span>{transaction.categoryName} · {transaction.date}</span></div><strong className={transaction.type === 'INCOME' ? 'positive-amount' : ''}>{transaction.type === 'INCOME' ? '+' : '-'}${Number(transaction.amount).toLocaleString('en-US', { minimumFractionDigits: 2 })}</strong><button className="delete-button" aria-label="Delete transaction" onClick={onDelete}><Trash2 size={16} /></button></div>
}

function ResourceForm({ section, accounts, categories, onClose, onCreated }: { section: Section; accounts: Account[]; categories: Category[]; onClose: () => void; onCreated: () => void }) {
  const [name, setName] = useState(''); const [amount, setAmount] = useState(''); const [type, setType] = useState<'INCOME' | 'EXPENSE'>('EXPENSE'); const [accountId, setAccountId] = useState(accounts[0]?.id.toString() || ''); const [categoryId, setCategoryId] = useState(''); const [month, setMonth] = useState(String(new Date().getMonth() + 1)); const [year, setYear] = useState(String(new Date().getFullYear())); const [currency, setCurrency] = useState('USD'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const filteredCategories = categories.filter((category) => category.type === type || category.type === 'BOTH')
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setSaving(true); try { if (section === 'accounts') await createAccount({ name, currency }); if (section === 'categories') await createCategory({ name, type, icon: '•', color: '#7450b5' }); if (section === 'transactions') await createTransaction({ amount: Number(amount), description: name, date: new Date().toISOString().slice(0, 10), type, accountId: Number(accountId), categoryId: Number(categoryId) }); if (section === 'budgets') await createBudget({ amount: Number(amount), month: Number(month), year: Number(year), accountId: Number(accountId), categoryId: Number(categoryId) }); onCreated() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to save this item.') } finally { setSaving(false) } }
  const label = section === 'accounts' ? 'account' : section.slice(0, -1)
  return <div className="modal-backdrop"><section className="transaction-modal resource-modal" role="dialog" aria-modal="true"><div className="modal-heading"><div><p className="kicker">NEW {section.toUpperCase()}</p><h2>Add {label}</h2></div><button className="modal-close" onClick={onClose}>×</button></div><form onSubmit={submit}>{section === 'accounts' && <><label>Name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Everyday checking" required /></label><label>Currency<select value={currency} onChange={(event) => setCurrency(event.target.value)}><option>USD</option><option>EUR</option><option>ARS</option></select></label></>}{section === 'categories' && <><label>Name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Groceries" required /></label><div className="type-toggle"><button type="button" className={type === 'EXPENSE' ? 'selected' : ''} onClick={() => setType('EXPENSE')}>Expense</button><button type="button" className={type === 'INCOME' ? 'selected' : ''} onClick={() => setType('INCOME')}>Income</button></div></>}{(section === 'transactions' || section === 'budgets') && <><label>Amount<input type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" required /></label>{section === 'transactions' && <><label>Description<input value={name} onChange={(event) => setName(event.target.value)} placeholder="What was this for?" /></label><div className="type-toggle"><button type="button" className={type === 'EXPENSE' ? 'selected' : ''} onClick={() => setType('EXPENSE')}>Expense</button><button type="button" className={type === 'INCOME' ? 'selected' : ''} onClick={() => setType('INCOME')}>Income</button></div></>}{section === 'budgets' && <div className="form-row"><label>Month<input type="number" min="1" max="12" value={month} onChange={(event) => setMonth(event.target.value)} required /></label><label>Year<input type="number" value={year} onChange={(event) => setYear(event.target.value)} required /></label></div>}<label>Account<select value={accountId} onChange={(event) => setAccountId(event.target.value)} required><option value="">Select account</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label>Category<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)} required><option value="">Select category</option>{filteredCategories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label></>}{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="cancel-button" onClick={onClose}>Cancel</button><button className="auth-submit" disabled={saving}>{saving ? 'Saving...' : 'Save'} <ArrowUpRight size={16} /></button></div></form></section></div>
}

export default ManagementView
